/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'tonykuo' at '2016/1/11 下午 5:46' with Gradle 2.3
 *
 * @author tonykuo, @date 2016/1/11 下午 5:46
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
