package com.patentdata.model;

// Generated 2016/1/17 下午 11:46:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Books generated by hbm2java
 */
@Entity
@Table(name="books"
)
public class Books  implements java.io.Serializable {


     private String isbn;
     private String title;
     private String subTitle;
     private String publisher;
     private Integer publishYear;
     private Integer pages;
     private String fileFormat;

    public Books() {
    }

	
    public Books(String isbn) {
        this.isbn = isbn;
    }
    public Books(String isbn, String title, String subTitle, String publisher, Integer publishYear, Integer pages, String fileFormat) {
       this.isbn = isbn;
       this.title = title;
       this.subTitle = subTitle;
       this.publisher = publisher;
       this.publishYear = publishYear;
       this.pages = pages;
       this.fileFormat = fileFormat;
    }
   
     @Id 

    
    @Column(name="isbn", nullable=false, length=13)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="sub_title")
    public String getSubTitle() {
        return this.subTitle;
    }
    
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    
    @Column(name="publisher")
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    
    @Column(name="publish_year")
    public Integer getPublishYear() {
        return this.publishYear;
    }
    
    public void setPublishYear(Integer publishYear) {
        this.publishYear = publishYear;
    }

    
    @Column(name="pages")
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    
    @Column(name="file_format")
    public String getFileFormat() {
        return this.fileFormat;
    }
    
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }




}


