/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'tonykuo' at '2016/1/11 下午 5:46' with Gradle 2.3
 *
 * @author tonykuo, @date 2016/1/11 下午 5:46
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    
    def "someLibraryMethod one"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
    
    def "someLibraryMethod two"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
    
    def "someLibraryMethod three"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
    
    def "someLibraryMethod four"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
    
    def "someLibraryMethod five"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
    
    def "someLibraryMethod six"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == false
    }
    
    def "someLibraryMethod seven"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == false
    }
    
    def "someLibraryMethod eight"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
    
}
